### ISSUE TITLE
restricted dates

### ISSUE THREAD

**Issue by rettinghaus** [correspSearch/CMIF-Creator#1]
Dates are restricted to be lower than `1999-12-31`. 
Dates after `2000-01-01` should work also!
On the other hand '0000' is accepted, also it isn't a valid date.

**Comment by Jomula** [comment]
That is true. As for `0000`, this will be regarded as an invalid entry from now on. For any entry later than 1999, there will be a warning but no error, the date will be regarded as being valid.
