### ISSUE TITLE
uncertain dates

### ISSUE THREAD

**Issue by wobweger** [correspSearch/CMIF-Creator#13]
I want to set date when uncertain attribute

+ went into CMIF Creator
+ set value
![20200722_071604](https://user-images.githubusercontent.com/40311784/88142574-0e44ba80-cbf6-11ea-9d7b-d47146328d35.png)
+ saved json file
![20200722_071616](https://user-images.githubusercontent.com/40311784/88142610-1ac91300-cbf6-11ea-8fe8-e0bac4f6c5a8.png)
![20200722_071621](https://user-images.githubusercontent.com/40311784/88142633-1f8dc700-cbf6-11ea-85d3-e84c07abf4ab.png)
  + which timezone is active on your machine, export was performed at `2020-07-22 07:16:21`
+ to my surprise attribute `evidence` has value `conjecture` set
  I expected attribute `cert` with value `low`
![20200722_071931](https://user-images.githubusercontent.com/40311784/88142666-2d434c80-cbf6-11ea-8e76-71ff25ec4540.png)
+ save xml file
![20200722_071641](https://user-images.githubusercontent.com/40311784/88142688-3af8d200-cbf6-11ea-8e76-cfea13e9b280.png)
+ to my surprise attribute `evidence` has value `conjecture` set
  I expected attribute `cert` with value `low`
![20200722_071827](https://user-images.githubusercontent.com/40311784/88142706-43510d00-cbf6-11ea-8250-f6e77faa472e.png)

just for fun, tried the other way too

+ CMIF Creator is showing data different as data
![20200722_082816](https://user-images.githubusercontent.com/40311784/88142766-5a8ffa80-cbf6-11ea-9e12-6991491a6695.png)
![20200722_082856](https://user-images.githubusercontent.com/40311784/88142789-624f9f00-cbf6-11ea-88f7-863d2b359d09.png)

please find xml and json files

[CMIF_Creator_20200723.zip](https://github.com/correspSearch/CMIF-Creator/files/4958268/CMIF_Creator_20200723.zip)

**Comment by Jomula** [comment]
Thank you very much for your detailed information on the issue. We will look into it asap.

**Comment by Jomula** [comment]
As it turned out, labels were swapped, the issue will be fixed in the next release 2.1.1.
Thanks again!
