### ISSUE TITLE
editor without email

### ISSUE THREAD

**Issue by rettinghaus** [correspSearch/CMIF-Creator#3]
`<email>` is not mandatory in `<editor>`, but without it, the file doesn't load properly (editor text is lost).

**Comment by Jomula** [comment]
After a discussion that `<email>` is indeed not mandatory in `<editor>` but useful to have for having a contact, we decided it to remain mandatory. However, if you load an existing file that does not contain `<email>`, there won't be an error from now on, so `<editor>` should load properly.
