### ISSUE TITLE
Wrong CC0 URL

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [correspSearch/CMIF-Creator#5]
When I select "CC0" as license, the generated link in the CMIF file, "https://creativecommons.org/licenses/by/null/", is dead. Perhaps "https://creativecommons.org/publicdomain/zero/1.0/" would be a better option.

**Comment by Jomula** [comment]
Dear Martin,
thank you for your message. We will have a look into the issues asap.
Best regards
Jonas

**Comment by Jomula** [comment]
the issue is fixed in the github build. it has yet to be published on correspSearch.
